In [1]:
import re
# 1 đoạn text được generate bởi chat-gpt
text = "I have always been curious about the way people use language to share ideas and emotions. When I first learned about Natural Language Processing, or NLP, I immediately felt excited. I love how this field allows machines to work with human language, " \
"making communication between humans and technology more natural."
# Tách theo dấu cách và dấu phẩy
parts = re.split(r'[ ,]+',text)
# Tạo các kí tự unique trong text
chars = sorted(list(set(parts)))
# Tạo tập vocabulary
vocab_size = len(chars)
vocab = {ch: i for i, ch in enumerate(chars)}
i2ch = {i:ch for ch, i in vocab.items()}

In [2]:
print(len(vocab))
print(vocab)

43
{'I': 0, 'Language': 1, 'NLP': 2, 'Natural': 3, 'Processing': 4, 'When': 5, 'about': 6, 'allows': 7, 'always': 8, 'and': 9, 'been': 10, 'between': 11, 'communication': 12, 'curious': 13, 'emotions.': 14, 'excited.': 15, 'felt': 16, 'field': 17, 'first': 18, 'have': 19, 'how': 20, 'human': 21, 'humans': 22, 'ideas': 23, 'immediately': 24, 'language': 25, 'learned': 26, 'love': 27, 'machines': 28, 'making': 29, 'more': 30, 'natural.': 31, 'or': 32, 'people': 33, 'share': 34, 'technology': 35, 'the': 36, 'this': 37, 'to': 38, 'use': 39, 'way': 40, 'with': 41, 'work': 42}


Scaled dot product attention

In [3]:
import numpy as np
def softmax(x):
    # softmax theo hàng
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x/np.sum(e_x, axis=-1, keepdims=True)
def scaled_dot_product_attention(Q, K, V):
    # Q: (n, d_k) - n query vectors
    # K: (m, d_k) - m key vectors
    # V: (m, d_v) - m value vectors
    # Lấy ra d_k cho bước tính căn bậc 2
    d_k = Q.shape[1]
    # Tính score
    scores = np.matmul(Q, K.T) / np.sqrt(d_k)
    # Tính trọng số attention
    weights = softmax(scores)
    # Tổ hợp tuyến tính với V
    output = np.matmul(weights, V)
    return output, weights



In [4]:
q = np.random.randn(3, 2)
q.shape
q.shape[1]

2

In [5]:
matrix1 = np.random.randn(3,2)
matrix2 = np.random.randn(2,4)
matrix3 = np.matmul(matrix1, matrix2)
print(f"matrix1:\n{matrix1}\nmatrix2:\n{matrix2}\nmatrix3:\n{matrix3}")

matrix1:
[[ 1.23670313 -0.63012639]
 [ 0.61493948 -1.32804036]
 [ 0.18802834  0.24452649]]
matrix2:
[[ 1.90903044 -0.05973812 -0.59936344 -1.54066961]
 [-1.29898438  1.63779264  0.56489028  1.35444008]]
matrix3:
[[ 3.17942825 -1.10589469 -1.09718692 -2.75881937]
 [ 2.89904188 -2.21179007 -1.11876934 -2.74616967]
 [ 0.04131573  0.38925123  0.02543333  0.04150694]]


Xử lý input

In [6]:
input = "I love NLP"
# Tạo các tokens
tokens = input.split()
# kích thước embedding
d_model = 4
# Tạo embedding cho tất cả các từ trong vocab
embedding_matrix = np.random.randn(len(vocab), d_model)
# Lấy embedding của các từ trong input
X = np.array([embedding_matrix[vocab[token]] for token in tokens])

In [7]:
print(f"Các tokens từ input:{tokens}")
print(f"Ma trận embeddings của input:\n{X}\n")
print(f"Ma trận embeddings của vocab:\n{embedding_matrix}")

Các tokens từ input:['I', 'love', 'NLP']
Ma trận embeddings của input:
[[-0.28414297  0.5105938  -1.28003813  0.1831562 ]
 [-1.18198904  0.16371034  0.81165581  1.72332232]
 [ 0.45015997  0.14041349  1.73605686  0.17712048]]

Ma trận embeddings của vocab:
[[-0.28414297  0.5105938  -1.28003813  0.1831562 ]
 [ 0.81911202  0.36481029  0.11954116  0.4827179 ]
 [ 0.45015997  0.14041349  1.73605686  0.17712048]
 [ 1.68602878  0.44443076  0.26031169  0.95772398]
 [ 1.60807753  0.67085487 -0.80519302  2.21333135]
 [ 1.10374902  0.94110533 -0.24039937 -0.85843129]
 [-0.94640359 -0.02819815  1.01729827  1.40293191]
 [-0.99254509  0.65798832  1.67795019 -0.69223624]
 [-0.48874065  0.76557697 -0.96661164  0.25306021]
 [ 0.62797331  0.5195788   0.60988437  0.40153634]
 [ 0.58307585 -0.41930423  0.32540663 -0.05718785]
 [-0.2766526  -0.51010248 -0.43140118  1.08323794]
 [-0.30534275 -0.94009895  0.06513127 -0.46292539]
 [ 1.35521774  0.24624491  0.41415694  1.24133455]
 [ 0.44285034 -0.13272086 -0.9

In [8]:
# Khởi tạo 3 ma trận query, key và value
W_Q = np.random.randn(d_model, d_model)
W_K = np.random.randn(d_model, d_model)
W_V = np.random.randn(d_model, d_model)
Q = np.matmul(X, W_Q)
K = np.matmul(X, W_K)
V = np.matmul(X, W_V)

In [9]:
print(f"Ma trận query Q:\n{Q}")
print(f"Ma trận key K:\n{K}")
print(f"Ma trận value V:\n{V}")

Ma trận query Q:
[[-1.33012562  1.74909821  4.80124788  1.14463139]
 [ 1.68870173  0.72124072 -0.05435431 -0.9269872 ]
 [ 1.57890416 -0.95539947 -5.61930671 -1.25690407]]
Ma trận key K:
[[-1.31754222 -1.58047639 -0.23005138  0.21123925]
 [ 4.56486092 -0.89278645 -0.55442181 -3.3704424 ]
 [ 2.3116382   2.25270999 -0.60917664 -1.87507933]]
Ma trận value V:
[[-1.84821711  0.16026191 -0.03048012  0.98777685]
 [-0.47927684 -2.13030977  1.36258939 -0.04069385]
 [ 2.30036403 -0.40444128  0.28837901 -1.9227005 ]]


In [10]:
output, attention_weights = scaled_dot_product_attention(Q, K, V)
print(f"Ma trận embeddings mới của từng từ biểu diễn thêm ngữ cảnh:\n{output}")
print(f"Ma trận trọng số (softmax):\n{attention_weights}")

Ma trận embeddings mới của từng từ biểu diễn thêm ngữ cảnh:
[[-0.86159299  0.02250952  0.04746528  0.29548939]
 [ 0.04311447 -1.80335058  1.15911143 -0.39430405]
 [-0.43326927 -2.09999847  1.34374124 -0.07178765]]
Ma trận trọng số (softmax):
[[7.61078281e-01 1.64122553e-03 2.37280493e-01]
 [8.30559088e-04 8.10825581e-01 1.88343860e-01]
 [5.55754677e-04 9.82618918e-01 1.68253274e-02]]


Từ ma trận trọng số (softmax): 

    "I" chú ý nhiều nhất vào "NLP"

    "love" chú ý nhiều nhất vào "I"

    "NLP" chú ý nhiều nhất vào "I"

Cài đặt Multi Head Attention

In [ ]:
class MultiHeadAttention:
    def __init__(self, d_model, num_heads):
        # d_model phải chia hết cho num_heads
        assert d_model % num_heads == 0
        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = d_model // num_heads
        # Khởi tạo các ma trận trọng số
        self.W_Q = np.random.randn(d_model, d_model)
        self.W_K = np.random.randn(d_model, d_model)
        self.W_V = np.random.randn(d_model, d_model)
        # Ma trận trọng số được sử dụng cuối cùng
        self.W_O = np.random.randn(d_model, d_model)
    def split_heads(self, x):
        seq_len, d_model = x.shape
        x = x.reshape(seq_len, self.num_heads, self.d_k)
        return x.transpose(1,0,2)
    def combine_heads(self, x):
        num_heads, seq_len, d_k = x.shape
        x = x.transpose(1, 0, 2).reshape(seq_len, self.d_model)
        return X

    def forward(self, Q, K, V):

SyntaxError: expected ':' (1866982784.py, line 1)