In [16]:
import re
# 1 đoạn text được generate bởi chat-gpt
text = "I have always been curious about the way people use language to share ideas and emotions. When I first learned about Natural Language Processing, or NLP, I immediately felt excited. I love how this field allows machines to work with human language, " \
"making communication between humans and technology more natural."
# Tách theo dấu cách và dấu phẩy
parts = re.split(r'[ ,]+',text)
# Tạo các kí tự unique trong text
chars = sorted(list(set(parts)))
# Tạo tập vocabulary
vocab_size = len(chars)
vocab = {ch: i for i, ch in enumerate(chars)}
i2ch = {i:ch for ch, i in vocab.items()}

In [17]:
print(len(vocab))
print(vocab)

43
{'I': 0, 'Language': 1, 'NLP': 2, 'Natural': 3, 'Processing': 4, 'When': 5, 'about': 6, 'allows': 7, 'always': 8, 'and': 9, 'been': 10, 'between': 11, 'communication': 12, 'curious': 13, 'emotions.': 14, 'excited.': 15, 'felt': 16, 'field': 17, 'first': 18, 'have': 19, 'how': 20, 'human': 21, 'humans': 22, 'ideas': 23, 'immediately': 24, 'language': 25, 'learned': 26, 'love': 27, 'machines': 28, 'making': 29, 'more': 30, 'natural.': 31, 'or': 32, 'people': 33, 'share': 34, 'technology': 35, 'the': 36, 'this': 37, 'to': 38, 'use': 39, 'way': 40, 'with': 41, 'work': 42}


Scaled dot product attention

In [ ]:
import numpy as np
def softmax(x):
    # softmax theo hàng
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x/np.sum(e_x, axis=-1, keepdims=True)
def scaled_dot_product_attention(Q, K, V):
    # Q: (n, d_k) - n query vectors
    # K: (m, d_k) - m key vectors
    # V: (m, d_v) - m value vectors
    # Lấy ra d_k cho bước tính căn bậc 2
    d_k = Q.shape[1]
    # Tính score
    scores = np.matmul(Q, K.T) / np.sqrt(d_k)
    # Tính trọng số attention
    weights = softmax(scores)
    # Tổ hợp tuyến tính với V
    output = np.matmul(weights, V)
    return output, weights



In [4]:
q = np.random.randn(3, 2)
q.shape
q.shape[1]

2

In [8]:
matrix1 = np.random.randn(3,2)
matrix2 = np.random.randn(2,4)
matrix3 = np.matmul(matrix1, matrix2)
print(f"matrix1:\n{matrix1}\nmatrix2:\n{matrix2}\nmatrix3:\n{matrix3}")

matrix1:
[[ 0.91803786  1.33468034]
 [ 1.61058011 -0.0389854 ]
 [ 0.9648097   0.07329329]]
matrix2:
[[ 0.13218212 -0.16805987  0.24882833  0.15038597]
 [-0.57862431 -0.54385326 -0.67723334 -1.29144218]]
matrix3:
[[-0.6509303  -0.88015558 -0.6754562  -1.58560247]
 [ 0.2354478  -0.24947154  0.42716018  0.29255605]
 [ 0.08512131 -0.20200659  0.19043533  0.0504398 ]]


Xử lý input

In [18]:
input = "I love NLP"
# Tạo các tokens
tokens = input.split()
# kích thước embedding
d_model = 4
# Tạo embedding cho tất cả các từ trong vocab
embedding_matrix = np.random.randn(len(vocab), d_model)
# Lấy embedding của các từ trong input
X = np.array([embedding_matrix[vocab[token]] for token in tokens])

In [24]:
print(f"Các tokens từ input:{tokens}")
print(f"Ma trận embeddings của input:\n{X}\n")
print(f"Ma trận embeddings của vocab:\n{embedding_matrix}")

Các tokens từ input:['I', 'love', 'NLP']
Ma trận embeddings của input:
[[-1.22853542  0.03819077  0.17830988 -1.04599879]
 [-0.68366229  0.76152901  0.37678591 -1.52470116]
 [ 0.53124668  0.58300333  0.13463916 -1.0122585 ]]

Ma trận embeddings của vocab:
[[-1.22853542e+00  3.81907672e-02  1.78309882e-01 -1.04599879e+00]
 [ 1.07587593e+00  5.50192265e-01  9.84862577e-01 -2.02896108e+00]
 [ 5.31246675e-01  5.83003331e-01  1.34639165e-01 -1.01225850e+00]
 [ 5.37751068e-01 -2.43157439e-01 -2.10053844e-01  3.44645072e-01]
 [ 3.29295182e-01 -8.76292435e-01  1.90284798e+00 -3.57668819e-01]
 [ 1.09155808e+00 -6.17995268e-01 -1.04692143e+00 -1.68485412e+00]
 [-8.23082036e-04 -5.75349939e-01 -2.93742997e+00  5.64622999e-01]
 [-2.53203834e-02  4.91033857e-01  7.06015783e-01 -4.51073793e-01]
 [-1.18636163e+00 -2.61088787e-01 -1.31245941e+00 -3.41492087e-01]
 [-9.84490886e-01 -9.05494366e-02 -1.76094763e+00  2.66056023e+00]
 [-6.29507618e-01  9.31553086e-01 -9.08698990e-01 -8.31635101e-01]
 [ 6.21

In [ ]:
# Khởi tạo 3 ma trận query, key và value
W_Q = np.random.randn(d_model, d_model)
W_K = np.random.randn(d_model, d_model)
W_V = np.random.randn(d_model, d_model)
Q = np.matmul(X, W_Q)
K = np.matmul(X, W_K)
V = np.matmul(X, W_V)

In [28]:
print(f"Ma trận query Q:\n{Q}")
print(f"Ma trận key K:\n{K}")
print(f"Ma trận value V:\n{V}")

Ma trận query Q:
[[-1.18576376  0.11915334 -0.17607655 -1.41910106]
 [-0.30805472  2.03866776  1.08077087 -1.52660935]
 [ 0.45034429  1.76594178  2.05207215  0.23599913]]
Ma trận key K:
[[ 0.33817901  0.86102341  2.60664518  0.58419291]
 [-0.42065747 -0.12934273  0.44547502 -0.20023977]
 [-0.96276848 -0.7852896  -1.35788857 -0.9417376 ]]
Ma trận value V:
[[ 0.60631719 -0.94991571  1.25436063  2.06484468]
 [-0.5627526  -0.54890609  2.55033553  0.79151612]
 [-1.0056897  -0.24148932  1.54858382 -0.99923429]]


In [29]:
output, attention_weights = scaled_dot_product_attention(Q, K, V)
print(f"Ma trận embeddings mới của từng từ biểu diễn thêm ngữ cảnh:\n{output}")
print(f"Ma trận trọng số (softmax):\n{attention_weights}")

Ma trận embeddings mới của từng từ biểu diễn thêm ngữ cảnh:
[[-0.7628135  -0.37676414  1.77824813 -0.29744167]
 [ 0.29562483 -0.83321547  1.50154328  1.6412237 ]
 [ 0.56311643 -0.93472356  1.29866405  2.01464758]]
Ma trận trọng số (softmax):
[[0.08112458 0.25308971 0.66578571]
 [0.75891916 0.17594287 0.06513798]
 [0.96395728 0.03363988 0.00240284]]


Từ ma trận trọng số (softmax): 

    "I" chú ý nhiều nhất vào "NLP"

    "love" chú ý nhiều nhất vào "I"

    "NLP" chú ý nhiều nhất vào "I"